### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by pavankay** [chuyangliu/snake#54]
I am getting this errror Traceback (most recent call last):
  File "/Users/bob/Downloads/snake-master/run.py", line 3, in <module>
    from snake.game import Game, GameConf, GameMode
  File "/Users/bob/Downloads/snake-master/snake/game.py", line 10, in <module>
    from snake.solver import DQNSolver, GreedySolver, HamiltonSolver
  File "/Users/bob/Downloads/snake-master/snake/solver/__init__.py", line 1, in <module>
    from snake.solver.dqn import DQNSolver
  File "/Users/bob/Downloads/snake-master/snake/solver/dqn/__init__.py", line 4, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by gravelBridge** [comment]
you didnt do pip -r requirements.txt, also try python -m pip install requirements.txt
